node {
    stage ('test') {
        sh 'echo Hello World'
    }
    stage ('cloning') {
        sh 'git clone https://github.com/Pravin-Kumar-GitHub/spring-petclinic.git'
    }
    stage ('building') {
        sh 'mvn package'
    }
}