pipeline {
    agent any
    stages {
        stage('testing') {
            steps {
                sh 'echo Hello, This is for testing'
            }
        }
        stage('cloning') {
            steps {
                git url: 'https://github.com/Pravin-Kumar-GitHub/spring-petclinic.git', 
                    branch: 'main'
            }
        }
        stage('building') {
            steps {
                sh 'mvn package'
            }
        }
        stage('archiving') {
            steps {
                archiveArtifacts '**/*.jar'
            }
        }
    }
}